#!/bin/bash

#ddev-generated
## Description: Run Shopware Messenger Queue
## Usage: shopware-queue [flags] [args]
## Example: "ddev shopware-queue"
## ProjectTypes: php

bin/console messenger:consume --time-limit=295
