#!/bin/bash

#ddev-generated
## Description: Builds the JavaScript for Shopawre
## Usage: shopware-watch-administration [flags] [args]
## Example: "ddev shopware-watch-administration"
## ProjectTypes: php


bash bin/watch-administration.sh

